spring:
  application:
    name: GeoFlow
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/geo_flow
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zazhi.geoflow.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

minio:
  endpoint: http://localhost:9000
  bucketName: minio-demo
  accessKey: YtDznxVyGgplz9qXl5bw
  secretKey: K4N9YbIUHifTm5ABkMWHidp8QN8YmYn7RmlsYSBz

jwt:
  secret: zazhi
  expiration: 1296000000