spring:
  profiles:
    active: dev
  application:
    name: GeoFlow

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zazhi.geoflow.controller
knife4j:
  enable: true
  setting:
    language: zh_cn

jwt:
  secret: zazhi
  expiration: 1296000000